### PR TITLE
Spacepoint formation algorithm change

### PR DESCRIPTION
**Pull request by arkslobodkins**
Changed block size to 256, launching with 1024 threads per block would cause 'too many resources requested for launch' on a desktop GPU.

### CODE REVIEW

**Review by krasznaa — APPROVED** [review]
👍

**Comment by stephenswat** [comment]
Hmm what GPU is this? The kernel is set to be launchable for 1024 threads;
perhaps the CUDA architecture you build with (`CMAKE_CUDA_ARCHITECTURES`)
does not match the device you are running on?

**Comment by stephenswat** [comment]
No, please do not merge this yet

**Comment by arkslobodkins** [comment]
I believe it's Nvidia RTX 500 Ada Generation Laptop GPU. CMAKE_CUDA_ARCHITECTURES was set to native in my CMakeLists so that flag should have propagated to traccc. Setting threads to 256 solves the issue...

**Pull request merged**
