### PR TITLE
Use surface link for module projection

### PR DESCRIPTION
**Pull request by beomki-yeo**
I think module links do not have to be used after clusterization. This also helps the currect refactoring of #692

### CODE REVIEW

**Comment by beomki-yeo** [comment]
Actually `module_link` can be dropped from the measurement as it is not used anywhere but some tests - this will be followed up later

**Comment by beomki-yeo** [comment]
@stephenswat Any thought?

**Comment by krasznaa** [comment]
I believe this is fine. But this PR by itself is really meaningless in my mind. For this to be meaningful, you should:
  - Remove the now unnecessary variable;
  - Remove the code that fills that unnecessary variable;
  - Do this change, which I believe is the last remaining client for this variable.

Could you add the first 2 points to this PR as well?

**Comment by beomki-yeo** [comment]
OK I removed the module link of measurements

**Comment by beomki-yeo** [comment]
@krasznaa Could you review the PR?

**Review by krasznaa — APPROVED** [review]
👍

**Pull request merged**
