### PR TITLE
Add additional output information to clustering algorithm

### PR DESCRIPTION
**Pull request by guilhermeAlmeida1**
This PR adds additional output information to the clustering algorithm, which allows linking back from the created spacepoints down to the cells they were created from. This is currently not used for anything, but will be necessary for physics performance testing with the new EDM.

### CODE REVIEW

**Comment by guilhermeAlmeida1** [comment]
> Nice speedy fix. What's the performance impact of this?

The actual kernel itself doesn't really become slower, which that was to be expected, but the extra allocation on the host seems to make the clustering some 25% slower from looking at profiles, but then again if I run the full throughput application it doesn't become any slower at all. So, I guess we can say there's no impact, sort of?

**Comment by stephenswat** [comment]
Yeah, the caching of memory allocations will handle this nicely in multi-event execution.

I will be around to collect on the bet we made about the performance of this on Monday! :wink:

**Review by krasznaa — APPROVED** [review]
We could dress up the data types into some more "reader friendly" classes in the future, but for now this looks good enough. The information we need is actually returned, so :+1:.

**Review by krasznaa — APPROVED** [review]
For cleanliness, could we all use the "Update with Rebase" button on the web interface? I'm not a fan of including all these "merge commits" in our history... :frowning: (**cough** *Stephen* **cough**... :stuck_out_tongue:)

**Comment by stephenswat** [comment]
I'm fine with that but then we should probably also rebase PRs instead of merging. :innocent: 

image

**Comment by stephenswat** [comment]
Also, looks like applying PRs by rebasing results in unverified comments if the committer is in vigilant mode... https://github.com/acts-project/traccc/commit/cd54f73583c8e31f43862a7afe6ff7d43060f7e5 :frowning_face:

**Pull request merged**
