### PR TITLE
Change the particle hypo of KF in case of charge is changed

### PR DESCRIPTION
**Pull request by beomki-yeo**
@stephenswat Can you test this if it does work? Otherwise please let me know the command line so I can reproduce

### CODE REVIEW

**Comment by stephenswat** [comment]
I tested this, but now the CKF seems to run forever... Very odd!

**Comment by beomki-yeo** [comment]
You mean KF runs forever? Or is this something independent

**Comment by beomki-yeo** [comment]
With this PR, I can run `mt_cuda` with ODD mu200 data (RelWithDebInfo build). Probably you need to wait a couple of minute because it took about 2 mins for warming up

**Review by stephenswat — APPROVED** [review]
Okay, then I'm happy. Thanks!

**Pull request merged**
