### PR TITLE
Updated readme to match current development status

### PR DESCRIPTION
**Pull request by guilhermeAlmeida1**

### CODE REVIEW

**Review by stephenswat — APPROVED** [review]

**Comment by stephenswat** [comment]
Actually, before we merge this could you fix the Mermaid graph as well?

**Review by stephenswat — CHANGES_REQUESTED** [review]
Actually, before we merge this could you fix the Mermaid graph as well?

**Comment by guilhermeAlmeida1** [comment]
> Actually, before we merge this could you fix the Mermaid graph as well?

I think this should be good now

**Review by stephenswat — APPROVED** [review]
Great, thanks! I would have added the new edges at the end of the graph but this also works of course. :smile:

**Pull request merged**
