### PR TITLE
Refactor Clusterization 

### PR DESCRIPTION
**Pull request by beomki-yeo**
The PR depends on #197 

Changes:
1. `component_connection` and `measurement_creation` now gets container input rather than collection input
2. Add `fill_measurement` function for both CPU and CUDA clusterization
3. Change cluster container header type to the index type (to reduce data written in GPU device)

SYCL clusterization gets faster with item 3, but CPU clusterization gets slower with item 1. We might be able to restore the CPU clusterization speed by smartly reserving the vector size (especially in `measurement_creation`) but I think that can be done later.

**Before**
```
 number of seeds (cpu): 5085
 number of seeds (sycl): 5085
 measurements matching rate: 0.999914
 spacepoint matching rate: 0.985082
 seed matching rate: 0.957522
 track parameters matching rate: 0.999607
==> Statistics ... 
- read    92504 spacepoints from 13565 modules
- created        321488 cells           
- created        92504 meaurements     
- created        92504 spacepoints     
- created (sycl) 92504 spacepoints     
- created (cpu)  5085 seeds
- created (sycl) 5085 seeds
==> Elpased time ... 
wall time           4.28865   
file reading (cpu)        1.1548    
clusterization_time (cpu) 0.014971  
spacepoint_formation_time (cpu) 0.0682879 
clusterization_time (sycl) 0.0168215 
seeding_time (cpu)        0.150847  
seeding_time (sycl)       0.011929  
tr_par_esti_time (cpu)    0.00188373
tr_par_esti_time (sycl)   0.00138263
```

**After**

```
 number of seeds (cpu): 5085
 number of seeds (sycl): 5085
 measurements matching rate: 0.999849
 spacepoint matching rate: 0.985114
 seed matching rate: 0.958702
 track parameters matching rate: 0.999213
==> Statistics ... 
- read    92504 spacepoints from 13565 modules
- created        321488 cells           
- created        92504 meaurements     
- created        92504 spacepoints     
- created (sycl) 92504 spacepoints     
- created (cpu)  5085 seeds
- created (sycl) 5085 seeds
==> Elpased time ... 
wall time           4.12956   
file reading (cpu)        1.12308   
clusterization_time (cpu) 0.0199605 
spacepoint_formation_time (cpu) 0.0571459 
clusterization_time (sycl) 0.0131576 
seeding_time (cpu)        0.137351  
seeding_time (sycl)       0.0120212 
tr_par_esti_time (cpu)    0.00155009
tr_par_esti_time (sycl)   0.00123775
```

### CODE REVIEW

**Review by konradkusiak97 — COMMENTED** [review]
Looks good to me :smiley: 
Just one thing, it seems we're going back and forth with @krasznaa  in terms of templating/untemplating `sparse_ccl`, I'm not sure which is the better approach :thinking:

**Comment by beomki-yeo** [comment]
The templating (original) is better I suppose. I just could not make it work with templating.

**Review by konradkusiak97 — APPROVED** [review]
I would opt for merging this in :+1:

**Comment by beomki-yeo** [comment]
OK Let me fix the CPU part later.

**Pull request merged**
