### PR TITLE
Enable tests for Alpaka builds

### PR DESCRIPTION
**Pull request by stephenswat**
Now that we have some Alpaka tests, we are ready to actually run them in the CI.

### CODE REVIEW

**Comment by stephenswat** [comment]
Interestingly, debug builds make Alpaka code so slow that it times out the CI. :thinking:

**Comment by krasznaa** [comment]
Two options we have here:
  - Increase the timeout from 1500 seconds to something larger.
  - Only test Alpaka in Release mode.

I'm not even sure which of these two bad options is the better one. But probably I'd go for the timeout increase. :thinking:

**Comment by stephenswat** [comment]
It's really interesting why the Alpaka code is so much slower; we could also try adding an `-O2` to the Alpaka build; also far from ideal, though.

**Comment by StewMH** [comment]
I think disabling for debug is fine.

**Comment by stephenswat** [comment]
Okay, I have updated this to run the Alpaka tests for release builds only.

**Review by paulgessinger — APPROVED** [review]

**Pull request merged**
