### PR TITLE
External packages only build when needed

### PR DESCRIPTION
**Pull request by guilhermeAlmeida1**
Minor improvement to the build reducing the fetched content to only what is actually getting used.

### CODE REVIEW

**Review by stephenswat — CHANGES_REQUESTED** [review]
Unless you have a good reason to do it this way, why not just go to https://github.com/acts-project/traccc/blob/main/CMakeLists.txt#L147 and change `if( TRACCC_SETUP_KOKKOS )` to `if( TRACCC_SETUP_KOKKOS AND TRACCC_BUILD_KOKKOS)`?

**Comment by guilhermeAlmeida1** [comment]
> Unless you have a good reason to do it this way, why not just go to https://github.com/acts-project/traccc/blob/main/CMakeLists.txt#L147 and change `if( TRACCC_SETUP_KOKKOS )` to `if( TRACCC_SETUP_KOKKOS AND TRACCC_BUILD_KOKKOS)`?

Oh, I had somehow missed these two "SETUP" flags.

**Comment by krasznaa** [comment]
Not even `AND` conditions! Just make the default value of the `SETUP` variables depend on the appropriate `BUILD` variables.

**Comment by guilhermeAlmeida1** [comment]
Thank you both for the help, I've changed this to the correct approach now

**Review by stephenswat — DISMISSED** [review]
Parece bom para mim

**Review by stephenswat — APPROVED** [review]
image

**Pull request merged**
