### PR TITLE
External Updates, main branch (2022.01.21.)

### PR DESCRIPTION
**Pull request by krasznaa**
These are all the necessary updates for switching this project to all the latest versions of [vecmem](https://github.com/acts-project/vecmem), [algebra-plugins](https://github.com/acts-project/algebra-plugins) and [detray](https://github.com/acts-project/detray). The PR switches to the releases:
  - https://github.com/acts-project/vecmem/releases/tag/v0.8.0
  - https://github.com/acts-project/algebra-plugins/releases/tag/v0.5.1
    * I made a bit of a boo-boo with the `v0.5.0` tag. :frowning:
  - https://github.com/acts-project/detray/releases/tag/v0.3.0

After making sure that all "algebra plugins" in this project would define `traccc::scalar` correctly (without relying on the now removed `algebra::scalar`), in the end I only had to update the use of `detray::grid2` and the Detray axes in a couple of places. @beomki-yeo, the "axis errors" were the ones scaring me at first. But it turned out that I just had to switch from `detray::axis::circular<>` to `detray::axis::circular` in a few places to make my compilers happy with the code. (Having to pass `vecmem::memory_resource` references to a few more places was a lot less scary of course.)

Though I'm still not entirely sure that I understand how that part of `detray::grid2` works. :frowning: But I guess that's not for this PR to sort out...

@konradkusiak97, this should help you with your development. Hopefully we'll be able to get it merged in quickly... (@stephenswat  and @paulgessinger :stuck_out_tongue:)

### CODE REVIEW

**Review by stephenswat — APPROVED** [review]
Looks harmless to me, I'm fine with merging this in when the CI passes.

**Comment by krasznaa** [comment]
Aargh... :frowning: CUDA 11.5 (which I used for my tests) is able to swallow Detray's code, but CUDA 11.3 (used in the CI) is not.

Let me make this into a draft for now, and go and fix the issue in Detray first...

**Comment by beomki-yeo** [comment]
It's really weird. If I look into the log, it seems the SFINAE in `detray::axis` is the culprit. 
But how is it possible..?  The SFINAE has existed since the older version of detray.

**Comment by beomki-yeo** [comment]
Oh. `axis_data` didn't exist in v0.2.0 detray. ok.. I will have a look

**Comment by krasznaa** [comment]
Don't bother Beomki! This is the PR that, as I explained yesterday, I believe is failing because of (a) bug(s) in CUDA 11.3. I will switch to CUDA 11.5 in this PR once https://github.com/acts-project/machines/pull/42 is in, and a new (git/docker) tag is made.

You shouldn't worry about this for now...

**Comment by stephenswat** [comment]
Just out of curiosity, have we tested this with CUDA 11.2 and 11.4? To me, this smells very strongly of a preprocessor issue. While I'm not saying it's not a bug in `nvcc`, I think the issue warrants some deeper analysis than flat-out asserting that that is the case. If it is incorrect use of the preprocessor then we should aim to fix that bug in our code, rather than so severely restrict the range of compatible compilers.

**Comment by krasznaa** [comment]
I spent all of Friday morning trying to understand which exact part of the code CUDA 11.3 is having a problem with. I wasn't able to figure this out in a few hours.

We can come back to it later on, but for now I'm desperate to be able to switch to the latest versions of algebra-plugins and detray. So if you want to do a deeper analysis, the floor is all yours...

**Comment by stephenswat** [comment]
After testing different versions on the `atspot01` machine:

| CUDA toolkit version | Works |
| --- | --- |
| 10.1.243 | :x: (expected) |
| 10.2.89  | :x: (expected) |
| 11.0.3   | :heavy_check_mark: |
| 11.1.1   | :heavy_check_mark: |
| 11.2.2   | :heavy_check_mark: |
| 11.3.1   | :x: |
| 11.4.3   | :x: |
| 11.5.0   | :heavy_check_mark: |
| 11.5.1   | :heavy_check_mark: |

**Review by stephenswat — APPROVED** [review]

**Pull request merged**
