### PR TITLE
Lower the values of qop stddevs

### PR DESCRIPTION
**Pull request by beomki-yeo**
The current stddev of qop is high which can change the sign of qop. This PR lowers the values of qop stddevs.

### CODE REVIEW

**Comment by krasznaa** [comment]
Sure, no objections here. Let me know once it goes out of draft status.

**Comment by beomki-yeo** [comment]
Yup, but it seems there is a fundamental problem deeper inside - investigating..

**Comment by beomki-yeo** [comment]
When the qop of initial track parameter gets very small (~0.001) by the high stddev, the sign of qop can change in the kalman updater. 

While the exact reason is unknown, I guess that the high deviation from truth value causes kalman fitter to make large numerical uncertainties.

**Comment by beomki-yeo** [comment]
Actually the stddev of q/p need to be given as something like 10% of truth q/p instead of a hard coded value. (Current examples will still break for >1000 GeV/c particles) But let's do that in the later PR

**Comment by beomki-yeo** [comment]
@krasznaa review?

**Pull request merged**
