### PR TITLE
Disable validate on push for policybot

### PR DESCRIPTION
**Pull request by beomki-yeo**
Let's see if this fixes the CI issue...

From: https://github.com/acts-project/acts/commit/d6c23c6ace5d974ac89bd852004efbc4a0c39634

### CODE REVIEW

**Comment by beomki-yeo** [comment]
Definitely a wrong idea...

**Comment by beomki-yeo** [comment]
Let me merge this without an approval

**Comment by beomki-yeo** [comment]
@asalzburger @paulgessinger It seems force-merging can be done by code maintainers only

**Comment by paulgessinger** [comment]
You mean overriding branch requirements?

**Comment by paulgessinger** [comment]
Concerning the policybot issue: I believe the my merged a fix now which allows disabling this globally in the installation. I can try to deploy this on Monday. Aside from that I think they have workaround for the lack of push info to invalidate in push. I'll check if that's available in their docker images yet.

**Comment by beomki-yeo** [comment]
Sounds good. :+1:

**Pull request merged**
