### PR TITLE
ci: Put test data into tar files, unpack them in the CI

### PR DESCRIPTION
**Pull request by paulgessinger**

### CODE REVIEW

**Review by krasznaa — CHANGES_REQUESTED** [review]
Please add some lines into `README.md` on what people should do when they clone the repository.

**Comment by krasznaa** [comment]
Please add the `REDME.md` update.

#@^&# gitlab.cern.ch has completely broken down by now. I can clone the HEAD of its master branch, but as soon as I try to switch to an older hash, things just break. (A direct clone of the repository succeeds to switch to an old hash after a while. But the timeout seems to be too long for git-submodule to accept. :thinking:)

To get the CI back into a working state, it seems that we must accept this PR as quickly as possible...

**Comment by paulgessinger** [comment]
How about this @krasznaa?

**Review by krasznaa — APPROVED** [review]
Yepp, let's get this in...

**Pull request merged**
