### PR TITLE
Improve the numerical stability of measurement variance calculation

### PR DESCRIPTION
**Pull request by stephenswat**
In the current measurement creation algorithm, the variance of measurement positions is calculated using a naive single-pass algorithm. This algorithm is extremely numerically unstable because it is prone to catastrophic cancellation. Especially when using floats (for GPU processing), this algorithm will not provide the necessary accuracy and will likely lead to nonsensical variance values being calculated.

In this commit, I update the measurement creation algorithm to use a weighted variation of Welford's algorithm, which is a numerically stable single-pass algorithm which can work for large numbers of activations as well as high coordinate ranges. This should improve the accuracy of the variance calculation significantly.

### CODE REVIEW

**Comment by beomki-yeo** [comment]
I think this can be merged

**Comment by paulgessinger** [comment]
This is in *preparation* for CCA unit tests, yes? 
Generally looks good to me.

**Comment by stephenswat** [comment]
Partially, yes. The main reason I want this to go in before the test suite is because the tests won't pass with the old variance code, because it doesn't give the correct results. :smile:

**Comment by paulgessinger** [comment]
Right. Would you be ok to link out or at least name the weighted variation of Welford's algorithm in the comment so readers can look it up if need be?

**Comment by stephenswat** [comment]
Great suggestion, I've added a comment block that links to the original paper, as well as a chapter of Knuth's _The Art of Computer Programming_ that explains this algorithm as well. :slightly_smiling_face:

**Review by krasznaa — APPROVED** [review]
Just because it seems that my approval gets PRs merged this morning, I think this one is ripe for a merge as well. :wink:

**Pull request merged**
