### PR TITLE
Update algebra-plugins and vecmem versions

### PR DESCRIPTION
**Pull request by StewMH**
Update algebra-plugins and vecmem to latest tags. Largely important for Alpaka HIP developments.

### CODE REVIEW

**Comment by StewMH** [comment]
Couple of test failures:
```
[ RUN      ] CkfToyDetectorValidation1/CkfToyDetectorTests.Run/0
WARNING: mask store has empty collection no. 2
WARNING: mask store has empty collection no. 3
WARNING: mask store has empty collection no. 6
WARNING: mask store has empty collection no. 7
WARNING: material store has empty collection no. 0
WARNING: material store has empty collection no. 1
WARNING: material store has empty collection no. 2
WARNING: material store has empty collection no. 4
WARNING: acceleration data structures store has empty collection no. 3
WARNING: acceleration data structures store has empty collection no. 4
WARNING: No entries in volume finder
Detector check: OK
unknown file: Failure
C++ exception with description "data.host_ptr()[0].capacity() (10000) != sizes[0] (3)" thrown in the test body.
```

**Comment by krasznaa** [comment]
It gets weirder and weirder... I can reproduce the test failures locally just fine. But when I try to run the test through `cuda-gdb`, I get:

```
Reading symbols from ./bin/traccc_test_cuda...
(cuda-gdb) run --gtest_filter="CkfToyDetectorValidation1/CkfToyDetectorTests.Run/0"
Starting program: /home/krasznaa/ATLAS/projects/traccc/build/bin/traccc_test_cuda --gtest_filter="CkfToyDetectorValidation1/CkfToyDetectorTests.Run/0"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffee1ff000 (LWP 3314102)]
[New Thread 0x7fffecdff000 (LWP 3314103)]
[Detaching after fork from child process 3314104]
The CUDA driver has hit an internal error.
Error code: 0xa
Further execution or debugging is unreliable.
Please ensure that your temporary directory is mounted with write and exec permissions.

(cuda-gdb)
```

First time I'm seeing such a thing. 😕 Time to simplify my build setup a bit... 🤔

**Comment by beomki-yeo** [comment]
When I implemented the test at the first time, it was working fine with my 2070. 
and AT SOME POINT OOM happens. I don't think this bug is fully on me.

**Comment by niermann999** [comment]
Are you running this after the recent detray update? There was one detray version where the grids ate a lot of memory. That *should* be fixed now

**Comment by beomki-yeo** [comment]
Let's jump to https://github.com/acts-project/traccc/pull/516

It is introduced by my past PR in trying to allow arbitrary big tracks

**Comment by krasznaa** [comment]
@StewMH, you should update this PR to: https://github.com/acts-project/vecmem/releases/tag/v1.3.1 We'll deal with all other issues in different places. 😉

**Comment by StewMH** [comment]
All done now, I did a rebase and then some local tests before committing 1.3.1.

**Review by krasznaa — APPROVED** [review]
With tests finally passing, let's finally merge this in. 🎉

**Pull request merged**
