### PR TITLE
update oneapi machine version

### PR DESCRIPTION
**Pull request by beomki-yeo**
Let me just test it...

### CODE REVIEW

**Comment by beomki-yeo** [comment]
Hmm,, How does this happen? 
```
 [ RUN      ] SparseCclAlgorithm/ConnectedComponentAnalysisTests.Run/single_module_multiple_hit_single_sparse_0000000007
/__w/traccc/traccc/tests/common/tests/cca_test.hpp:124: Failure
The difference between match->variance[1] and io_truth.variance1 is 9.7218866348266602, which exceeds tol, where
match->variance[1] evaluates to 9.7218866348266602,
io_truth.variance1 evaluates to 0, and
tol evaluates to 0.99550002813339233.
/__w/traccc/traccc/tests/common/tests/cca_test.hpp:123: Failure
The difference between match->variance[0] and io_truth.variance0 is 3.7385613918304443, which exceeds tol, where
match->variance[0] evaluates to -3.7385613918304443,
io_truth.variance0 evaluates to 0, and
tol evaluates to 0.76569998264312744.
/__w/traccc/traccc/tests/common/tests/cca_test.hpp:123: Failure
The difference between match->variance[0] and io_truth.variance0 is 9.4132928848266602, which exceeds tol, where
match->variance[0] evaluates to 9.4132928848266602,
io_truth.variance0 evaluates to 0, and
tol evaluates to 0.96390002965927124.
/__w/traccc/traccc/tests/common/tests/cca_test.hpp:124: Failure
The difference between match->variance[1] and io_truth.variance1 is 3.1808722019195557, which exceeds tol, where
match->variance[1] evaluates to 3.1808722019195557,
io_truth.variance1 evaluates to 8.2718061255302767e-25, and
tol evaluates to 0.78439998626708984.
```

**Comment by stephenswat** [comment]
That is very mysterious... :thinking:

**Comment by beomki-yeo** [comment]
I think it's a bug in sycl compiler

**Comment by beomki-yeo** [comment]
It's fixed now

**Review by stephenswat — APPROVED** [review]
Fantastic, let's get it in then!

**Pull request merged**
