### PR TITLE
Ambiguity Resolution: remove duplicate measurements for each track

### PR DESCRIPTION
**Pull request by SylvainJoube**
This PR ensures that the greedy solver deals with tracks that have unique measurement IDs, removing duplicates, if any.

I was able to replicate the issue with the `geant4_ttbar_mu20` data provided by Attila on PR [Data V7, main branch (2024.05.03.) #561](https://github.com/acts-project/traccc/pull/561) and the command line written at the beginning of issue [Ambiguity Resolution Errors on ODD ttbar Simulation (2024.05.04.) #564](https://github.com/acts-project/traccc/issues/564).

It turns out that I did not anticipate that a track could be made of the same `measurement_id` several times. This happened twice on the generated data from `geant4_ttbar_mu20`: for tracks 1176 and 720, that’s why the greedy solver was showing an error. The same “error” should exist on ACTS too, since the Greedy Solver code remains mostly unchanged. I have just taken a look at file [`Core/include/Acts/AmbiguityResolution/GreedyAmbiguityResolution.ipp` from ACTS](https://github.com/acts-project/acts/blob/67acd8ab6eb3f2b0d422e769211552f9d94bc579/Core/include/Acts/AmbiguityResolution/GreedyAmbiguityResolution.ipp#L44).

For example, in issue [Ambiguity Resolution Errors on ODD ttbar Simulation (2024.05.04.) #564](https://github.com/acts-project/traccc/issues/564), the track of index 720 has measurements: 2878 4167 5155 15837 15837, with 15837 twice.

I could have changed the `std::vector<std::size_t> measurements` into a `std::set<std::size_t>` but I'm not sure of the performance implications of such a change, and I'm a little short on time, so this is a quick fix!

### CODE REVIEW

**Review by krasznaa — CHANGES_REQUESTED** [review]
It's excellent that you understood where the issues / error messages come from.

But I'm not convinced that this should be "fixed" in the ambiguity resolution algorithm. :thinking: Making the algorithm robust against such input is absolutely good. But the track finding should really not be attaching the same measurement multiple times to the same track.

@beomki-yeo, how would this happen? Looping tracks? :confused:

For now, this sort of a check seems good. (Just making the thing into a warning.) But eventually, once the track finding is not expected to produce such tracks, I would demote these checks into assertions. I.e. something like:

```c++
assert([&]() {
    // code that decides whether there are measurement duplicates on a track
    }() == false);
```

(I've been thinking recently about adding a few more of such assertions into our algorithms...)

**Comment by SylvainJoube** [comment]
Thank you for your feedback Attila!

I’ve modified the code to clearly display a single warning message per track with duplicate measurements. It can handle multiple duplicate measurements without being too verbose. The output now displays:

```
WARNING: @greedy_ambiguity_resolution_algorithm: Track 1171 has duplicated measurement(s): 15195 (2 times). Measurement list: 3291 3475 4518 7396 8617 9632 9625 10484 15195 15195 15269 15268

WARNING: @greedy_ambiguity_resolution_algorithm: Track 720 has duplicated measurement(s): 15837 (2 times). Measurement list: 2878 4167 5155 15837 15837
```

**Review by krasznaa — APPROVED** [review]
Okay, let's go for this. :+1:

**Comment by SylvainJoube** [comment]
@krasznaa @beomki-yeo ping 🦊

**Comment by krasznaa** [comment]
Ahh, shoot... I thought with the approval in place you would be able to merge it yourself. Completely forgot about this... :frowning:

**Comment by SylvainJoube** [comment]
Thank you Attila! No worries, I was just afraid that, as time went by, I would have complicated merge conflicts :’)

**Comment by krasznaa** [comment]
Unfortunately we have a lot of traffic on the repository today, so my auto-merge will most likely not work anymore. But let's see... Since the CI takes a long time to run right now, we might as well wait for it to finish, and only rebase the PR if really needed.

**Comment by SylvainJoube** [comment]
Okay, we'll wait then! The `CI Bridge` says `Pipeline refused` though, is it an issue or should we wait?

**Comment by beomki-yeo** [comment]
I dont know how it would happen. But as @krasznaa mentioned, this is not something to be fixed from ambiguity solver. At least, this kind of things should be documented somewhere cleary (e.g. issues)

@SylvainJoube Does this issue cause a serious problem in the final result? Otherwise, I would suggest documenting this in the issue category instead of fixing it in the ambiguity solver. Then someone will be able to try to handle the issue by fiximg the CKF or whatever.

**Review by beomki-yeo — CHANGES_REQUESTED** [review]
The multiple module id should be understood better rather than fixing it in the ambiguity solver. For example, I would try to increase the configurarion value of minimal distance to reach the next surface in the finding_config.

**Comment by beomki-yeo** [comment]
I don't get why @krasznaa merged this PR after I requested the change.

**Comment by krasznaa** [comment]
I was curious when the question would come.

This was because of auto-merge. You made your comment Beomki, but didn't de-activate the auto-merge that was active on the PR. So when the CI finally finished, and nobody else merged another PR to prevent this from getting merged (as happened once earlier that day), it finally went in.

So now we know that when there is one approval and one change request on a PR, GitHub considers the PR approved. 🤔

It's a bit unfortunate indeed, but I personally didn't consider this PR too hurtful. If you check the discussion on it, I agree with you that the ambiguity resolution is not the place to sort this issue out. At the same time, this looked like an okay intermediate relief for #564.

So now, it's time to start looking for a real fix. 😉

**Comment by beomki-yeo** [comment]
I didn't know that the auto merge was activated. The PR itself is not very hurtful but I think we don't have to rush in merging PRs.

**Comment by krasznaa** [comment]
This was an unfortunate series of events. But "rushing" is a strange way to describe it. I approved this PR weeks ago. It was not something brand new.

**Comment by beomki-yeo** [comment]
Fine. Didn't even realize that i was pinged that long time ago - I was too busy with other affairs before the vacation.

Still, this duplicate ID problem needs to posted in the issue rather being left behind and forgotten eventually.

**Pull request merged**
